name: Supabase Keep-Alive

on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"query": "SELECT 1"}' \
            "$DATABASE_URL"

